version: 2

project_name: slotter

before:
  hooks:
    - go mod tidy

builds:
  - id: slotter
    main: ./cmd/slotter
    binary: slotter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
        -X github.com/kokoichi206/cal-slotter/internal/version.Version={{ .Version }}
        -X github.com/kokoichi206/cal-slotter/internal/version.Commit={{ .Commit }}
        -X github.com/kokoichi206/cal-slotter/internal/version.Date={{ .Date }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: slotter
    ids:
      - slotter
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: kokoichi206
    name: cal-slotter
